Repository codestates-seb/seb43_main_027, pull requests merged in 2023-05, with the labels that each got.

#71 :style: design: 리셋css,임시로고파일
  client/src/App.tsx
  client/src/asset/Buddy.png
  client/src/asset/Inddy.png
  client/src/react-app-env.d.ts
  client/src/styles/globalStyles.js
Labels: FE, UI

#76 ✨ feat: 버튼컴포넌트
  client/src/asset/logo.png
  client/src/components/elements/Button.tsx
  client/src/components/elements/elements.md
  client/src/pages/pages.md
  client/src/types/componentsTypes.ts
  client/src/types/types.md
Labels: FE

#91 ✨ feat: 회원가입 1차 완성
  client/src/App.tsx
  client/src/components/common/InputContainer.tsx
  client/src/components/elements/Button.tsx
  client/src/components/elements/Input.tsx
  client/src/components/elements/Label.tsx
  client/src/hooks/useInput.ts
  client/src/pages/SignUp/MoveToLogInBtn.tsx
  client/src/pages/SignUp/SULogo.tsx
  client/src/pages/SignUp/SignUp.tsx
  client/src/pages/SignUp/SignUpBtn.tsx
  client/src/pages/SignUp/SignUpButtonsContainer.tsx
  client/src/pages/SignUp/SignUpFieldsContainer.tsx
  client/src/pages/SignUp/SignUpOauthBtn.tsx
  client/src/pages/SignUp/SignUpOauthContainer.tsx
  client/src/pages/SignUp/SignUpTopWrapper.tsx
  client/src/styles/globalStyles.js
  client/src/types/componentsTypes.ts
  client/src/types/costomHooksTypes.ts
Labels: 기능, FE, UI

#96 feat : 게시글 삭제 기능
  server/inddybuddy/src/main/java/codejejus/inddybuddy/post/Post.java
  server/inddybuddy/src/main/java/codejejus/inddybuddy/post/PostController.java
  server/inddybuddy/src/main/java/codejejus/inddybuddy/post/PostMapper.java
  server/inddybuddy/src/main/java/codejejus/inddybuddy/post/PostService.java
Labels: BE, 기능

#99 Fe feat/게임채널
  client/src/App.tsx
  client/src/components/common/CategoryTag.tsx
  client/src/components/common/FilterTap.tsx
  client/src/components/common/SelectTag.tsx
  client/src/components/elements/Button.tsx
  client/src/data/dummyCategories.ts
  client/src/layouts/CategoryGames/GameItem.tsx
  client/src/layouts/CategoryGames/GameList.tsx
  client/src/layouts/CategoryGames/MainContainer.tsx
  client/src/layouts/GameChannel/GameTitle.tsx
  client/src/layouts/GameChannel/PostItem.tsx
  client/src/layouts/GameChannel/PostList.tsx
  client/src/pages/CategoryGames.tsx
  client/src/pages/GameChannel.tsx
  client/src/styles/globalStyles.js
Labels: 기능, FE, UI

#101 ✨ 홈-카테고리 기능 추가
  client/src/components/common/CategoryCard.tsx
  client/src/components/common/GameCard.tsx
  client/src/components/common/PostItem.tsx
  client/src/components/ui/Badge.tsx
  client/src/data/categoryIcons.tsx
  client/src/hooks/useFetch.ts
  client/src/layouts/Home/CategoryContainer.tsx
  client/src/layouts/Nav/UserNavItem.tsx
  client/src/types/dataTypes.ts
Labels: 기능, FE, UI

#100 feat : 게시글 태그&정렬 전체 조회 기능
  server/inddybuddy/src/main/java/codejejus/inddybuddy/global/constant/Filter.java
  server/inddybuddy/src/main/java/codejejus/inddybuddy/post/Post.java
  server/inddybuddy/src/main/java/codejejus/inddybuddy/post/PostController.java
  server/inddybuddy/src/main/java/codejejus/inddybuddy/post/PostDto.java
  server/inddybuddy/src/main/java/codejejus/inddybuddy/post/PostMapper.java
  server/inddybuddy/src/main/java/codejejus/inddybuddy/post/PostRepository.java
  server/inddybuddy/src/main/java/codejejus/inddybuddy/post/PostService.java
Labels: BE, 기능

#102 feat : 게시글 단일 조회
  server/inddybuddy/src/main/java/codejejus/inddybuddy/post/Post.java
  server/inddybuddy/src/main/java/codejejus/inddybuddy/post/PostController.java
  server/inddybuddy/src/main/java/codejejus/inddybuddy/post/PostDto.java
  server/inddybuddy/src/main/java/codejejus/inddybuddy/post/PostMapper.java
  server/inddybuddy/src/main/java/codejejus/inddybuddy/post/PostService.java
Labels: BE, 기능

#107 Fe feat/게임채널
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/common/FilterTap.tsx
  client/src/data/dummyPostList.ts
  client/src/data/filterTapList.ts
  client/src/data/postOptionTags.ts
  client/src/layouts/GameChannel/GameTitle.tsx
  client/src/layouts/GameChannel/PostItem.tsx
  client/src/layouts/GameChannel/PostList.tsx
  client/src/pages/CategoryGames.tsx
  client/src/pages/GameChannel.tsx
  client/src/styles/styles.md
Labels: 기능, FE

#106 Fe feat/네비게이션 기능
  client/src/layouts/Nav/NavContent.tsx
Labels: 기능, FE

#108 Fe feat/카테고리 페이지
  client/src/App.tsx
  client/src/data/dummyCategories.ts
  client/src/layouts/CategoryGames/GameItem.tsx
  client/src/layouts/CategoryGames/GameList.tsx
  client/src/layouts/CategoryGames/RecommendGames.tsx
  client/src/layouts/CategoryGames/TitleCategory.tsx
  client/src/layouts/GameChannel/GameTitle.tsx
  client/src/pages/CategoryGames.tsx
  client/src/types/propsTypes.ts
Labels: 기능, FE

#123 Fe feat/카테고리
  client/src/App.tsx
  client/src/asset/MainBanner.png
  client/src/asset/asset.md
  client/src/components/CategoryGames/GameItem.tsx
  client/src/components/CategoryGames/GameList.tsx
  client/src/components/CategoryGames/RecommendGames.tsx
  client/src/components/CategoryGames/TitleCategory.tsx
  client/src/components/GameChannel/GameTitle.tsx
  client/src/components/GameChannel/PostItem.tsx
  client/src/components/GameChannel/PostList.tsx
  client/src/components/common/CategoryTag.tsx
  client/src/data/dummyCategories.ts
  client/src/hooks/useInput.ts
  client/src/hooks/useValidity.ts
  client/src/layouts/CategoryGames/GameList.tsx
  client/src/pages/CategoryGames.tsx
  client/src/pages/GameChannel.tsx
  client/src/pages/LogIn/LogInFieldsContainer.tsx
  client/src/styles/globalStyles.js
  client/src/types/dataTypes.ts
  client/src/types/propsTypes.ts
Labels: 기능, FE

#133 Fe fect/게임채널
  client/src/App.tsx
  client/src/components/CategoryGames/GameItem.tsx
  client/src/components/CategoryGames/GameList.tsx
  client/src/components/CategoryGames/RecommendGames.tsx
  client/src/constants/constants.md
  client/src/constants/pathUrl.ts
  client/src/constants/stringMessage.ts
  client/src/types/dataTypes.ts
Labels: 기능, FE

#134 ✨ 게시글 작성페이지 기능 구현
  client/src/AppRoutes.tsx
  client/src/components/Home/FilterBar.tsx
  client/src/components/Home/GameContainer.tsx
  client/src/components/Home/HomeGameCard.tsx
  client/src/components/Posting/ImageSection.tsx
  client/src/components/Posting/InputSection.tsx
  client/src/components/common/GameCard.tsx
  client/src/constants/pathUrl.ts
  client/src/layouts/Nav/NavContent.tsx
  client/src/pages/LogIn/LogIn.tsx
  client/src/pages/SignUp/SignUp.tsx
  client/src/types/dataTypes.ts
  client/src/utils/postingValidate.ts
  client/src/utils/utils.md
  client/src/utils/validatePost.ts
Labels: 기능, FE

#138 Fe feat/게임채널
  client/src/components/CategoryGames/GameList.tsx
  client/src/components/CategoryGames/RecommendGames.tsx
  client/src/components/CategoryGames/TitleCategory.tsx
  client/src/components/GameChannel/GameTitle.tsx
  client/src/components/GameChannel/PostItem.tsx
  client/src/components/GameChannel/PostList.tsx
  client/src/components/common/CategoryCard.tsx
  client/src/components/common/Loading.tsx
  client/src/constants/pathUrl.ts
  client/src/data/categoryData.tsx
  client/src/data/dummyCategories.ts
  client/src/data/postOptionTags.ts
  client/src/pages/GameChannel.tsx
  client/src/types/dataTypes.ts
  client/src/types/propsTypes.ts
Labels: 기능, FE

#150 Fe feat/게임채널
  client/src/components/CategoryGames/GameList.tsx
  client/src/components/CategoryGames/TitleCategory.tsx
  client/src/components/GameChannel/GameTitle.tsx
  client/src/components/GameChannel/PostItem.tsx
  client/src/components/GameChannel/PostList.tsx
  client/src/data/dummyPostList.ts
  client/src/pages/GameChannel.tsx
  client/src/types/dataTypes.ts
Labels: 기능, FE

#154 ♻️ refactor: 대규모 리펙토링 및 파일이름변경/이동 , 커스텀 훅 수정
  client/src/AppRoutes.tsx
  client/src/components/GameRegister/CustomImageSection.tsx
  client/src/components/GameRegister/GameRegisterImageSection.tsx
  client/src/components/GameRegister/ImagePreview.tsx
  client/src/components/Home/CategoryContainer.tsx
  client/src/components/Login/LogInButton.tsx
  client/src/components/Login/LogInButtonsContainer.tsx
  client/src/components/Login/LogInFieldsContainer.tsx
  client/src/components/Login/LogInLogo.tsx
  client/src/components/Login/LogInOauthBtn.tsx
  client/src/components/Login/LogInOauthContainer.tsx
  client/src/components/Login/LogInTopWrapper.tsx
  client/src/components/Login/MoveToSignUpButton.tsx
  client/src/components/Login/googleLogin.tsx
  client/src/components/Signup/MoveToLoginBtn.tsx
  client/src/components/Signup/SignupBtn.tsx
  client/src/components/Signup/SignupButtonsContainer.tsx
  client/src/components/Signup/SignupFieldsContainer.tsx
  client/src/components/Signup/SignupOauthBtn.tsx
  client/src/components/Signup/SignupOauthContainer.tsx
  client/src/components/Signup/SignupTopWrapper.tsx
  client/src/components/Signup/SinupLogo.tsx
  client/src/components/common/InputContainer.tsx
  client/src/components/elements/Input.tsx
  client/src/data/gameTags.ts
  client/src/hooks/useInput.ts
  client/src/hooks/useValidation.ts
  client/src/hooks/useValidity.ts
  client/src/pages/GameRegister.tsx
  client/src/pages/LogIn/LogInButton.tsx
  client/src/pages/LogIn/LogInFieldsContainer.tsx
  client/src/pages/LogIn/LogInFieldsInputContainer.tsx
  client/src/pages/LogIn/LogInOauthBtn.tsx
  client/src/pages/LogIn/LogInOauthContainer.tsx
  client/src/pages/Login.tsx
  client/src/pages/SignUp/SignUp.tsx
  client/src/pages/SignUp/SignUpBtn.tsx
  client/src/pages/SignUp/SignUpFieldsContainer.tsx
  client/src/pages/SignUp/SignUpFieldsInputContainer.tsx
  client/src/pages/SignUp/SignUpOauthBtn.tsx
  client/src/pages/Signup.tsx
  client/src/slice/signupSlice.ts
  client/src/store/store.ts
  client/src/types/componentsTypes.ts
  client/src/types/customHooksTypes.ts
  client/src/types/dataTypes.ts
  client/src/types/utilTypes.ts
  client/src/utils/EmailSignUpFunction.ts
  client/src/utils/OauthSignUpFunction.ts
Labels: FE

#160 Fe feat/세부기능구현
  client/src/App.tsx
  client/src/api/apiCollection.ts
  client/src/components/Home/CategoryContainer.tsx
  client/src/components/Home/FilterBar.tsx
  client/src/components/Home/GameContainer.tsx
  client/src/components/Posting/InputSection.tsx
  client/src/components/common/GameCard.tsx
  client/src/components/common/PostItem.tsx
  client/src/hooks/useCheckAuth.ts
  client/src/hooks/useValidation.ts
  client/src/layouts/Header/Logo.tsx
  client/src/layouts/Nav/NavContent.tsx
  client/src/layouts/Nav/NavGameCardContainer.tsx
  client/src/layouts/Nav/UserNavItem.tsx
  client/src/pages/Posting.tsx
Labels: 기능, FE, UI

#169 ♻️ refactor: Oauth 로그인 수정
  client/src/AppRoutes.tsx
  client/src/components/Login/googleLogin.tsx
  client/src/constants/pathUrl.ts
  client/src/hooks/useValidation.ts
  client/src/layouts/Header/SearchBar.tsx
  client/src/pages/GameRegister.tsx
  client/src/pages/Login.tsx
  client/src/pages/Search.tsx
  client/src/types/dataTypes.ts
  client/src/utils/EmailSignUpFunction.ts
  client/src/utils/OauthSignUpFunction.ts
Labels: FE

#184 Be feat/기능 고도화 대댓글 기능 만들기
  server/inddybuddy/src/main/java/codejejus/inddybuddy/comment/Comment.java
  server/inddybuddy/src/main/java/codejejus/inddybuddy/comment/CommentController.java
  server/inddybuddy/src/main/java/codejejus/inddybuddy/comment/CommentDto.java
  server/inddybuddy/src/main/java/codejejus/inddybuddy/comment/CommentMapper.java
  server/inddybuddy/src/main/java/codejejus/inddybuddy/comment/CommentRepository.java
  server/inddybuddy/src/main/java/codejejus/inddybuddy/comment/CommentService.java
  server/inddybuddy/src/main/java/codejejus/inddybuddy/post/PostMapper.java
Labels: BE, 기능

#192 feat : 댓글 생성시 댓글 정보 반환 추가
  server/inddybuddy/src/main/java/codejejus/inddybuddy/comment/CommentController.java
  server/inddybuddy/src/main/java/codejejus/inddybuddy/comment/CommentService.java
Labels: BE, 기능

#195 ✨ 게시글상세페이지 및 부가 기능 구현
  client/src/components/Home/CategoryContainer.tsx
  client/src/components/Message/MessageOutput.tsx
  client/src/components/Posting/InputSection.tsx
  client/src/components/Posts/CommentInput.tsx
  client/src/components/Posts/CommentItem.tsx
  client/src/components/Posts/CommentSection.tsx
  client/src/components/Posts/PostInfo.tsx
  client/src/components/Posts/ReCommentInput.tsx
  client/src/components/Posts/ReCommentItem.tsx
  client/src/components/Posts/Title.tsx
  client/src/components/common/PostItem.tsx
  client/src/data/initialData.ts
  client/src/layouts/Nav/Nav.tsx
  client/src/layouts/Nav/NavContent.tsx
  client/src/pages/Message.tsx
  client/src/pages/Posts.tsx
  client/src/types/dataTypes.ts
Labels: 기능, FE, UI
